name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build
        run: pip install build

      - name: Build wheel
        run: python -m build

      - name: Prepare config
        run: |
          mkdir build

          # единый конфиг
          cat > build/config.json <<EOF
          {
            "workspace_base_path": "/Workspace/Users/igor.kovalchuk@sigma.software/project",
            "cluster_id": "0204-133055-sdmbqxte"
          }
          EOF

          cp dist/*.whl build/app.whl

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Upload to Workspace
        run: |
          DATE=$(date +%Y-%m-%d_%H-%M-%S)

          BASE_PATH=$(cat build/config.json | python -c "import sys, json; print(json.load(sys.stdin)['workspace_base_path'])")
          TARGET_PATH="$BASE_PATH/$DATE"

          echo "TARGET_PATH=$TARGET_PATH" >> $GITHUB_ENV

          databricks workspace mkdirs "$TARGET_PATH"

          databricks workspace import build/app.whl "$TARGET_PATH/app.whl" \
            --format SOURCE \
            --language PYTHON \
            --overwrite

          databricks workspace import build/config.json "$TARGET_PATH/config.json" \
            --format SOURCE \
            --language PYTHON \
            --overwrite

      - name: Generate terraform vars
        run: |
          CLUSTER_ID=$(cat build/config.json | python -c "import sys, json; print(json.load(sys.stdin)['cluster_id'])")

          cat > terraform/config.auto.tfvars <<EOF
          whl_base_path = "${{ env.TARGET_PATH }}"
          whl_file_name = "app.whl"
          cluster_id    = "$CLUSTER_ID"

          databricks_host  = "${{ secrets.DATABRICKS_HOST }}"
          databricks_token = "${{ secrets.DATABRICKS_TOKEN }}"
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve